### ISSUE TITLE
Collisions just don't exist

### ISSUE THREAD

**Issue by pancreasio** [fedepvg/Gradius#1]
I shoot nothing happens lol.

**Comment by Asplomer** [comment]
they actually happen but you cant see them, also shooting and just collisions in general are 2 different issues alltogether
![sepuedellegaraperder](https://user-images.githubusercontent.com/21362755/47574226-82fd9e80-d915-11e8-97e7-29c219bc7621.png)

**Comment by fedepvg** [comment]
Solucionado en el ultimo commit
