### ISSUE TITLE
[Gameplay] no aparecen los sprites en pantalla

### ISSUE THREAD

**Issue by Asplomer** [fedepvg/Gradius#2]
no los muestra en ambas versiones, aunque parecen funcionar las colisiones

**Comment by Asplomer** [comment]
lo unico que se puede ver son las balas, no esta cargando los sprite
![errorconlossprites](https://user-images.githubusercontent.com/21362755/47576999-37022800-d91c-11e8-9b6a-7077eaf4953c.png)

**Comment by fedepvg** [comment]
Solucionado, era un problema del gitignore
