### ISSUE TITLE
Errores, cosas para agregar

### ISSUE THREAD

**Issue by mbpmm** [fedepvg/Gradius#3]
-No hay sonido por lo tanto no se si funcionan los botones para activarlo o desactivarlo.
-Los disparos no colisionan con los asteroides, por lo tanto no hay manera de ganar.
-Las colisiones en la parte superior e inferior son raras, o me parece que no coinciden bien con la nave.
-aguante boke

**Comment by fedepvg** [comment]
Solucionado en la v1.0
