### ISSUE TITLE
[Folders] las carpetas de release estan en lugares por defecto

### ISSUE THREAD

**Issue by Asplomer** [fedepvg/Gradius#4]
hay que cambiar en las propiedades de configuracion - general - los directorios de salida y en intermedio
camibando (en salida): $(SolutionDir)bin\$(Configuration)\)
por : $(SolutionDir)bin\$(Platform)\$(Configuration)\)
y
cambiando(en intermedio): $(SolutionDir)obj\$(Configuration)\
por:$(SolutionDir)obj\$(Platform)\$(Configuration)\

**Comment by fedepvg** [comment]
Esa configuracion si esta aplicada
